### ISSUE TITLE
factory generation fails when injecting a nested class with a generic parameter

### ISSUE THREAD

**Issue by RBusarow** [square/anvil#244]
Kotlin 1.4.32 or 1.5.0-M2
Anvil 2.2.1

given this code:

``` Kotlin
package com.example

class Other {
  class Inner<T>
}
      
class InjectClass @Inject constructor(
  val inner: Other.Inner<String>
)
```
Compilation fails because it assumes any generic `KtUserType` which is qualified is _fully_ qualified.  So it attempts to resolve `Other.Inner`, but doesn't do so safely.

Exception:
```
com.squareup.anvil.compiler.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve fqName.
File being compiled: (10,14) in [...]

	at com.squareup.anvil.compiler.codegen.KotlinPoetKt$requireTypeName$2.invoke(KotlinPoet.kt:140)
	at com.squareup.anvil.compiler.codegen.KotlinPoetKt.requireTypeName(KotlinPoet.kt:210)
	at com.squareup.anvil.compiler.codegen.KotlinPoetKt.mapToParameter(KotlinPoet.kt:282)
	at com.squareup.anvil.compiler.codegen.dagger.InjectConstructorFactoryGenerator.generateFactoryClass(InjectConstructorFactoryGenerator.kt:61)
	at com.squareup.anvil.compiler.codegen.dagger.InjectConstructorFactoryGenerator.generateCodePrivate(InjectConstructorFactoryGenerator.kt:47)
	at com.squareup.anvil.compiler.codegen.PrivateCodeGenerator.generateCode(PrivateCodeGenerator.kt:19)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension$analysisCompleted$2.invoke(CodeGenerationExtension.kt:57)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:62)
[...]
```

**Comment by vRallev** [comment]
I did not realize how long it took me to release a stable version with the fix. I'm very sorry. Please ping me next time in case I forget again.

**Comment by RBusarow** [comment]
Heh...  I forgot that I actually had to keep kapt in a module because of this one.  I updated the Anvil version and didn't enable factory generation.  So thanks for the comment and reminder! 😄
