### ISSUE TITLE
Generated types cannot be injected with factory generation

### ISSUE THREAD

**Issue by RBusarow** [square/anvil#283]
This is a follow-up to my comment here: https://github.com/square/anvil/pull/267#issuecomment-841836847

I would like to inject generated code into manually written constructors, with the generated code directory added to source sets thanks to #207.  The code is generated using a custom `CodeGenerator` implementation.  This doesn't work with factory generation enabled, because Anvil cannot resolve types for the generated code even if it has already been written.

For example, this code:
``` Kotlin
package com.squareup.test
      
import javax.inject.Inject
      
class InjectClass @Inject constructor(
  val generatedClass: GeneratedClass
)
```

will generate this exception:
```
e: [...]/sources/src/main/java/com/squareup/test/Source.kt: (6, 23): com.squareup.anvil.compiler.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve fqName.
File being compiled: (6,23) in [...]/sources/src/main/java/com/squareup/test/Source.kt

	at com.squareup.anvil.compiler.codegen.KotlinPoetKt$requireTypeName$2.invoke(KotlinPoet.kt:124)
	at com.squareup.anvil.compiler.codegen.KotlinPoetKt.requireTypeName(KotlinPoet.kt:194)
	at com.squareup.anvil.compiler.codegen.KotlinPoetKt.mapToParameter(KotlinPoet.kt:266)
	at com.squareup.anvil.compiler.codegen.dagger.InjectConstructorFactoryGenerator.generateFactoryClass(InjectConstructorFactoryGenerator.kt:82)
	at com.squareup.anvil.compiler.codegen.dagger.InjectConstructorFactoryGenerator.generateCodePrivate(InjectConstructorFactoryGenerator.kt:58)
	at com.squareup.anvil.compiler.codegen.PrivateCodeGenerator.generateCode(PrivateCodeGenerator.kt:20)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension$analysisCompleted$2.invoke(CodeGenerationExtension.kt:61)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:63)
```

It will always fail on the very first pass of the code generators, whenever `InjectConstructorFactoryGenerator` is invoked.

Because all code generation happens within a single invocation of `CodeGenerationExtension.analysisCompleted(...)`, the `ModuleDescriptor` argument never contains the generated files.

Ultimately, this means that `ModuleDescriptor.findClassOrTypeAlias` will fail to resolve an `FqName` for generated code.  In turn, this means that `PsiElement.requireFqName(module)` and `FqName.asClassName(module)` will fail.  Those two functions are used all over the place.

Because there are so many different paths, it would be really awkward to pass additional parameters (like the codeGenDir or a list of generated files) to those two functions.

The best solution I could come up with would be to introduce an `AnvilModuleDescriptor` type, which is basically just a decorator for the `ModuleDescriptor` provided by `CodeGenerationExtension`.  It would add a single function - `resolveFqNameOrNull` - which would replace the existing `findClassOrTypeAlias` (which is only ever used for the `FqName`).  This new function falls back to checking generated code for matches if the normal PSI methods return nothing.

I've put up a draft for review here: #282

**Comment by vRallev** [comment]
Thanks for the detailed explanation and draft. I'm currently working on integration tests and ran into a similar issue for an unsupported use case. I agree that this needs to be resolved.

**Comment by vRallev** [comment]
I have a sample to reproduce the issue now. I also built a fix based on your draft. The idea was great!

**Comment by vRallev** [comment]
@RBusarow Could you give my solution a try and please report back if that works for you now?

**Comment by RBusarow** [comment]
Yep @vRallev, thank you!

**Comment by vRallev** [comment]
Wonderful!
