### ISSUE TITLE
Gradle plugin 1.0.5-1.4-M3 throws NoSuchMethodError on non-Android Kotlin project

### ISSUE THREAD

**Issue by dlam** [square/anvil#39]
I haven't looked too hard, but I think any AGP dependencies in AnvilPlugin need to be done in an optionally configured way?

I think this is the related file:
https://github.com/square/anvil/blob/3b58a5758b6d1fc56b388ff82980f435e39114b7/gradle-plugin/src/main/java/com/squareup/anvil/plugin/IncrementalSignal.kt

```
java.lang.NoSuchMethodError: 'java.io.Closeable com.android.build.gradle.internal.workeractions.WorkerActionServiceRegistry.registerServiceAsCloseable(com.android.build.gradle.internal.workeractions.WorkerActionServiceRegistry$ServiceKey, java.lang.Object)'
        at com.squareup.anvil.plugin.IncrementalSignalBuildService.registerIncrementalSignalService(IncrementalSignal.kt:69)
        at com.squareup.anvil.plugin.IncrementalSignalBuildService.registerIncrementalSignalService$default(IncrementalSignal.kt:64)
        at com.squareup.anvil.plugin.IncrementalSignalKt.registerIncrementalSignalBuildService(IncrementalSignal.kt:27)
        at com.squareup.anvil.plugin.AnvilPlugin.disableIncrementalKotlinCompilation(AnvilPlugin.kt:119)
        at com.squareup.anvil.plugin.AnvilPlugin.realApply(AnvilPlugin.kt:64)
        at com.squareup.anvil.plugin.AnvilPlugin.access$realApply(AnvilPlugin.kt:25)
        at com.squareup.anvil.plugin.AnvilPlugin$apply$3.invoke(AnvilPlugin.kt:47)
        at com.squareup.anvil.plugin.AnvilPlugin$apply$3.invoke(AnvilPlugin.kt:25)
        at com.squareup.anvil.plugin.AnvilPlugin$apply$1$1.execute(AnvilPlugin.kt:35)
        at com.squareup.anvil.plugin.AnvilPlugin$apply$1$1.execute(AnvilPlugin.kt:25)
```

**Comment by vRallev** [comment]
How can I reproduce the issue? Can you provide a sample? Which Gradle version are you using?

**Comment by dlam** [comment]
```
IntelliJ IDEA 2020.1.4 (Community Edition)
Build #IC-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.3.0-62-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1925M
Cores: 8
Non-Bundled Plugins: IdeaVIM, org.jetbrains.kotlin, com.markskelton.one-dark-theme
```

My gradle version is: distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

Let me see if I can put together a simple repro. I'm in a project with both android and kotlin only modules, but it fails from CLI building the kotlin-only module for me.

**Comment by vRallev** [comment]
I assumed that you'd use an older Gradle version. A sample project would be super useful.

**Comment by dlam** [comment]
Here it is! https://github.com/dlam/anvil-sample

You can basically comment out this line to repro / un-repro
https://github.com/dlam/anvil-sample/blob/master/app/build.gradle.kts#L3

**Comment by dlam** [comment]
I think this line needs to go into the if block or into a lazy configure block that only runs if it finds the Android extensions. 

https://github.com/square/anvil/blob/3b58a5758b6d1fc56b388ff82980f435e39114b7/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L119

I'm also using .kts so that might be contributing to the problem here

**Comment by vRallev** [comment]
You're using a very old Gradle version: `https\://services.gradle.org/distributions/gradle-6.1.1-bin.zip` Can you try a newer one?

**Comment by dlam** [comment]
Sorry updated - not sure why my IJ defaults to such an old version. Same error with 6.5.1, I think that's the latest?

**Comment by vRallev** [comment]
Thanks, that's very helpful. I missed in the review that the plugin now somehow depends on the Android Gradle Plugin. I'll take a look.

**Comment by vRallev** [comment]
The reason it doesn't fail in this project itself is that the Android Gradle Plugin is added to the root project's classpath.
