### ISSUE TITLE
Couldn't resolve ClassReference for kotlin.IllegalStateException File is unknown

### ISSUE THREAD

**Issue by JohnBuhanan** [square/anvil#445]
I'm seeing this right now after latest Snapshot.

```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve ClassReference for kotlin.IllegalStateException
File is unknown
```

Struggling to understand it and reproduce it in my sample project.

Will update this issue when I get it.

**Comment by JohnBuhanan** [comment]
```
com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve ClassReference for kotlin.RuntimeException
File is unknown

	at com.squareup.anvil.compiler.internal.ClassReferenceKt.requireClassReference(ClassReference.kt:86)
	at com.squareup.anvil.compiler.internal.ClassReferenceKt$directSuperClassReferences$3.invoke(ClassReference.kt:129)
	at com.squareup.anvil.compiler.internal.ClassReferenceKt$directSuperClassReferences$3.invoke(ClassReference.kt:129)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.next(Sequences.kt:299)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:169)
	at com.squareup.anvil.compiler.internal.ClassReferenceKt$allSuperTypeClassReferences$1.invoke(ClassReference.kt:108)
	at com.squareup.anvil.compiler.internal.ClassReferenceKt$allSuperTypeClassReferences$1.invoke(ClassReference.kt:104)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:570)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.squareup.anvil.compiler.codegen.dagger.MembersInjectionUtilsKt.memberInjectParameters(MembersInjectionUtils.kt:89)
	at com.squareup.anvil.compiler.codegen.dagger.MembersInjectorGenerator.generateCodePrivate(MembersInjectorGenerator.kt:49)
	at com.squareup.anvil.compiler.codegen.PrivateCodeGenerator.generateCode(PrivateCodeGenerator.kt:21)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$generateCode(CodeGenerationExtension.kt:93)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$invokeExtensionsOnAnalysisComplete(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:252)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:243)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:243)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:90)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1574)
	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by JohnBuhanan** [comment]
Sweet, I got it! My poorly named project now has the described issue in it:
https://github.com/JohnBuhanan/anvil-factory-generation-members-injector-issue

Basically something like this:
```
class SomeException : IllegalStateException {
    constructor(message: String, cause: Throwable) : super(message, cause)

    constructor(message: String) : super(message)

    constructor(cause: Throwable) : super(cause)
}
```

It is based on java.lang.IllegalStateException, but compile seems to be hunting for kotlin.IllegalStateException.

**Comment by JohnBuhanan** [comment]
Fully qualifying seems to be a good workaround:
```
class SomeException : java.lang.IllegalStateException {
```

**Comment by RBusarow** [comment]
Yep, I just reproduced the same thing.  Here's the absolute bare minimum:

```kotlin
package com.squareup.test 

class MyException : IllegalStateException()
```

All the Kotlin exceptions are just typealiases of the `java.lang.*` versions.

Since that definition exists in a different module (stdlib), we're trying to resolve a `ClassDescriptor` using the FqName of `kotlin.IllegalStateException`, and it fails.

This isn't just isolated to those exceptions, but they're convenient examples.  The problem should exist for any typealias which is defined in a different module.

I can start working on a solution for this in a little bit.

**Comment by JohnBuhanan** [comment]
Sweetness!  Thank you much :)

**Comment by JohnBuhanan** [comment]
@RBusarow This seems similar but maybe unrelated to typealiases across modules:
```
sealed class Base {
    sealed class Error : Base() {
        object Thing : Error()
    }
}
```

gives:
```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve ClassReference for kotlin.Error
File is unknown
```

**Comment by JohnBuhanan** [comment]
And this one seems to be trying to make `dagger.internal.Factory`

```
class Factory @Inject constructor(...
```

```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve FqName dagger.`internal`.Factory<Factory> for Psi element: dagger.`internal`.Factory<Factory>
```

**Comment by JohnBuhanan** [comment]
Like I mentioned in last comment, this is broken:
```
class Factory @Inject constructor() {}
```

But I just found out that this functional interface is also broken.
```
fun interface Factory {
    fun foo()
}

class Bar @Inject constructor(val thing2: Factory)
```

**Comment by RBusarow** [comment]
@JohnBuhanan I can't reproduce any issues with the `Factory` declarations, including with your reproducer project.  The ``dagger.`internal`.Factory`` reference is almost certainly legitimate and not just an ambiguity issue.  

Every class with constructor injection gets a generated factory class.  For instance, a constructor-injected class `Foo` requires a generated `class Foo_Factory : dagger.internal.Factory<Foo> { ... }`.

My best guess is that perhaps the real project doesn't have the `implementation 'com.google.dagger:dagger:2.40.5'` dependency?  From the error message, it looks like Anvil's unable to resolve that ``dagger.`internal`.Factory`` type.

**Comment by JohnBuhanan** [comment]
I think as I was devising those two examples they were conflicting with each other and giving me a false positive...

**Comment by JohnBuhanan** [comment]
But you're right, if I do one at a time and clean between them it seems to work.

**Comment by JohnBuhanan** [comment]
I think I found a new one
``` 
Back-end (JVM) Internal error: Couldn't resolve ClassReference for kotlin.Comparator
```

**Comment by RBusarow** [comment]
> I think I found a new one
> 
> ```
> Back-end (JVM) Internal error: Couldn't resolve ClassReference for kotlin.Comparator
> ```

Sorry for the delayed response, but thanks for reporting this one.

A generic typealias which doesn't need an import...  Fun stuff!

I'll look into this.

**Comment by JohnBuhanan** [comment]
You're okay. Happy to be here, thank you.

**Comment by vRallev** [comment]
@JohnBuhanan I struggle to understand if this ticket is still an issue and what exactly is failing. Can you maybe explain the code again that is currently failing for you?

**Comment by JohnBuhanan** [comment]
@RBusarow do you remember how to reproduce this?

My hunch is something like this?

```
interface SomeComparator : Comparator<Int> {
    override fun compare(o1: Int, o2: Int): Int
}

@ContributesBinding(Singleton::class)
class SomeComparatorImpl @Inject constructor() : SomeComparator {
    override fun compare(o1: Int, o2: Int): Int = 0
}
```

**Comment by RBusarow** [comment]
@JohnBuhanan I was unable to reproduce the Comparator one.  That's pretty much what I tried as well.

Here's a few tests for reproducing the other issues mentioned in this issue: https://github.com/square/anvil/pull/451/files#diff-8f0e0444685e9b28db9f07351e6dbe80c0016b7cbe52cb09b3b66ce439e06587

`Comparator`'s unique in that it's a stdlib (so no import) typealias with a generic, but it works in tests like those.

**Comment by JohnBuhanan** [comment]
Okay, I'm guessing there is no issue then @vRallev  :)
