### ISSUE TITLE
AnvilCompilationException with @ContributesSubcomponent.Factory and multiple @MergeComponent

### ISSUE THREAD

**Issue by SteinerOk** [square/anvil#464]
My test project contains two modules: lib and app. 
In lib module I described scopes:
```
public abstract class EntryScope private constructor()
public abstract class L1Scope private constructor()
public abstract class L2Scope private constructor()
```
and Subcomponents:
```
@ContributesSubcomponent(
    scope = L1Scope::class,
    parentScope = EntryScope::class
)
@SingleIn(L1Scope::class)
public interface L1Component {

    @ContributesTo(EntryScope::class)
    public interface ParentComponent {
        public fun l1Component(): L1Component
    }
}

@ContributesSubcomponent(
    scope = L2Scope::class,
    parentScope = L1Scope::class
)
@SingleIn(L2Scope::class)
public interface L2Component {

    @ContributesSubcomponent.Factory
    public interface Factory {
        public fun create(@BindsInstance value: Int): L2Component
    }

    @ContributesTo(L1Scope::class)
    public interface ParentComponent {
        public fun l2ComponentFactory(): Factory
    }
}
```
In app module I described two Components with same scope:
```
@MergeComponent(EntryScope::class)
@SingleIn(EntryScope::class)
interface Entry1Component {

    @Component.Factory
    interface Factory {
        fun create(@BindsInstance app: AnvilSampleApplication): Entry1Component
    }
}

@MergeComponent(EntryScope::class)
@SingleIn(EntryScope::class)
interface Entry2Component {

    @Component.Factory
    interface Factory {
        fun create(@BindsInstance app: AnvilSampleApplication): Entry2Component
    }
}
```
When I build project I received his error:
```
com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: There are multiple contributed bindings with the same bound type. The bound type is org2.steinerok.L2Component.Factory. The contributed binding classes are: [anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry1component.l1componenta.L2ComponentA.SubcomponentFactory, anvil.component.ua2.steinerok.experiment.entry2component.l1componenta.L2ComponentA.SubcomponentFactory]
File is unknown

	at com.squareup.anvil.compiler.codegen.BindingModuleGeneratorKt.findHighestPriorityBinding(BindingModuleGenerator.kt:375)
	at com.squareup.anvil.compiler.codegen.BindingModuleGeneratorKt.access$findHighestPriorityBinding(BindingModuleGenerator.kt:1)
	at com.squareup.anvil.compiler.codegen.BindingModuleGenerator.flush$lambda-13$getContributedBindingClasses(BindingModuleGenerator.kt:248)
	at com.squareup.anvil.compiler.codegen.BindingModuleGenerator.flush(BindingModuleGenerator.kt:256)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$flush(CodeGenerationExtension.kt:99)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:110)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
But, if I remove **@ContributesSubcomponent.Factory** usage and replace it to:
```
@ContributesSubcomponent(
    scope = L2Scope::class,
    parentScope = L1Scope::class
)
@SingleIn(L2Scope::class)
public interface L2Component {

    @ContributesTo(L1Scope::class)
    public interface ParentComponent {
        public fun l2Component(): L2Component
    }
}
```
and project build fine.

Maybe this is the correct behavior, but it seems strange to me ...

**Comment by ursusursus** [comment]
I think its same as mine https://github.com/square/anvil/issues/459

**Comment by vRallev** [comment]
Yes. That looks to be the same issue. Closing as duplicate.
