### ISSUE TITLE
Incremental compilation issue with ModuleDescriptor.getKtClassOrObjectOrNull

### ISSUE THREAD

**Issue by gmarques33** [square/anvil#567]
When Kotlin incremental compilation is enabled the `ModuleDescriptor.getKtClassOrObjectOrNull(FqName)` method returns null sometimes.

I created [this repo](https://github.com/gmarques33/KotlinIncrementalCompilationBug) reproducing the issue.

When I first compile the code the `getKtClassOrObjectOrNull` [here](https://github.com/gmarques33/KotlinIncrementalCompilationBug/blob/master/anvil-plugin/src/main/java/com/gmarques/anvilplugin/MyCodeGenerator.kt#L41) won't return null, but if I change [MyClass](https://github.com/gmarques33/KotlinIncrementalCompilationBug/blob/master/app/src/main/java/com/gmarques/incremental/MyClass.kt#L5) and compile again it will fail with the following exception:
```
> Task :app:compileDebugKotlin FAILED
e: java.lang.Exception: Should not be null!
        at com.gmarques.anvilplugin.MyCodeGenerator$generateCode$2.invoke(MyCodeGenerator.kt:44)
        at com.gmarques.anvilplugin.MyCodeGenerator$generateCode$2.invoke(MyCodeGenerator.kt:32)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
        at com.gmarques.anvilplugin.MyCodeGenerator.generateCode(MyCodeGenerator.kt:57)
        at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$generateCode(CodeGenerationExtension.kt:96)
        at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:131)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:434)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:120)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:357)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:299)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:159)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:622)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:100)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1713)
        at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

# Steps to reproduce:
1) Run ./gradlew :app:compileKotlin
2) Change [MyClass](https://github.com/gmarques33/KotlinIncrementalCompilationBug/blob/master/app/src/main/java/com/gmarques/incremental/MyClass.kt#L5). Add a new method or any new statement.
3) Run ./gradlew :app:compileKotlin again.

Sometimes it won't fail on the first try, but on the second or third time it always fail.

# Versions used:
Anvil 2.3.11-1-6-10
Kotlin 1.6.10
 
With Kotlin 1.5.31 and Anvil 2.3.11 I also had this issue, but when it happened I could just compile the project again and it would work. With Kotlin 1.6.10 when it happens it will only go away with a clean. It won't happen if `kotlin.incremental` is set to false.

**Comment by gmarques33** [comment]
I just tested with Anvil 2.4.0-M1. It is a lot easier to get the constructor parameters type name and the issue isn't happening.

https://github.com/gmarques33/KotlinIncrementalCompilationBug/compare/gmarques/2.4.0-M1

**Comment by vRallev** [comment]
Thanks for testing the latest release. Seems like there's no issue anymore :-)
