### ISSUE TITLE
StackOverflow when calling ClassReference.directSuperClassReferences()

### ISSUE THREAD

**Issue by gmarques33** [square/anvil#587]
If I have the following structure:
```kotlin
abstract class OuterClass {
    interface InnerInterface
}

class ClassA : OuterClass {
    class ClassB : InnerInterface
}
```

And I call `directSuperClassReferences()` when a code generator is processing  `ClassB` I expected to get a list with just one element, the ClassReference to InnerInterface, but I get a StackOverflow with the following stacktrace:
```
e: java.lang.StackOverflowError
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:109)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:58)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:118)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:137)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi$directSuperClassReferences$2.invoke(ClassReference.kt:164)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi$directSuperClassReferences$2.invoke(ClassReference.kt:163)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi.getDirectSuperClassReferences(ClassReference.kt:163)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi.directSuperClassReferences(ClassReference.kt:211)
	at com.squareup.anvil.compiler.internal.reference.ClassReferenceKt$allSuperTypeClassReferences$1.invoke(ClassReference.kt:390)
	at com.squareup.anvil.compiler.internal.reference.ClassReferenceKt$allSuperTypeClassReferences$1.invoke(ClassReference.kt:388)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:570)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.findClassReferenceInSuperTypes(PsiUtils.kt:283)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:256)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:118)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:137)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi$directSuperClassReferences$2.invoke(ClassReference.kt:164)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi$directSuperClassReferences$2.invoke(ClassReference.kt:163)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi.getDirectSuperClassReferences(ClassReference.kt:163)
	at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi.directSuperClassReferences(ClassReference.kt:211)
	at com.squareup.anvil.compiler.internal.reference.ClassReferenceKt$allSuperTypeClassReferences$1.invoke(ClassReference.kt:390)
	at com.squareup.anvil.compiler.internal.reference.ClassReferenceKt$allSuperTypeClassReferences$1.invoke(ClassReference.kt:388)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:570)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.findClassReferenceInSuperTypes(PsiUtils.kt:283)
	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:256)
```

Here's a test and a code generator reproducing the issue:
https://github.com/gmarques33/KotlinIncrementalCompilationBug/blob/gmarques/stack-overflow/anvil-plugin/src/test/java/com/gmarques/anvilplugin/MyCodeGeneratorTest.kt

https://github.com/gmarques33/KotlinIncrementalCompilationBug/blob/gmarques/stack-overflow/anvil-plugin/src/main/java/com/gmarques/anvilplugin/MyCodeGenerator.kt

**Comment by vRallev** [comment]
I tried the sample and cannot reproduce the issue. I created a test here #588 (and fixed an unrelated bug).

**Comment by gmarques33** [comment]
Thank you for the quick reply. I noticed that the `directSuperClassReferences()` from 2.4.0 doesn't exist anymore on 2.4.1-SNAPSHOT, and the new `directSuperTypeReferences()` doesn't throw the exception.

I tried to run your test with version 2.4.1-SNAPSHOT and the line
```kotlin
"ClassB" -> {
  assertThat(ref.directSuperTypeReferences()).hasSize(1)
}
```

does return an array with size 1, but I still see an stackoverflow, not sure if the unrelated bug that you fixed will fix this.
<img width="1295" alt="Screenshot 2022-04-01 at 19 23 22" src="https://user-images.githubusercontent.com/1514555/161349823-2a08c901-1ff4-48be-b67a-8fcfd9522310.png">

Anyway, I needed to get the super class and `ref.directSuperTypeReferences()[0].declaringClass.fqName` does return what I need in 2.4.1.

Please, close the issue if you think there's nothing wrong here.

**Comment by gmarques33** [comment]
The `allSuperTypeClassReferences()` throws StackOverflowError for this case.
Changing the test to:
```kotlin
"ClassB" -> {
    assertThat(ref.allSuperTypeClassReferences().toList()).hasSize(1)
}
```

will cause it to fail.

**Comment by vRallev** [comment]
Thanks, I can reproduce it now!
