### ISSUE TITLE
Backend Internal error: Exception during psi2ir when using with kotlin 1.8.20

### ISSUE THREAD

**Issue by jakoss** [square/anvil#702]
After upgrading kotlin to 1.8.20 i have this error during compilation:

```
org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during psi2ir
File being compiled: (25,84) in /Users/jakubsyty/Projects/AndroidArchitectureTemplate/app/build/anvil/src-gen-debug/pl/jsyty/architecturetemplate/GeneratedApplicationComponent.kt
The root cause org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionException was thrown at: org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionGenerator.generateErrorCall(ErrorExpressionGenerator.kt:100)
null: KtCallExpression:
factory()
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:253)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:237)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:75)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassMemberDeclaration(DeclarationGenerator.kt:101)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateMembersDeclaredInClassBody(ClassGenerator.kt:491)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass(ClassGenerator.kt:101)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass$default(ClassGenerator.kt:63)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassOrObjectDeclaration(DeclarationGenerator.kt:108)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:53)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateSingleFile(ModuleGenerator.kt:73)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateModuleFragment(ModuleGenerator.kt:53)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:97)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:224)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:57)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:41)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.contextForStubGeneration(Kapt3Extension.kt:280)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:174)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:104)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:125)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:182)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1486)
	at jdk.internal.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionException: null: KtCallExpression:
factory()
	at org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionGenerator.generateErrorCall(ErrorExpressionGenerator.kt:100)
	at org.jetbrains.kotlin.psi2ir.generators.StatementGenerator.visitCallExpression(StatementGenerator.kt:390)
	at org.jetbrains.kotlin.psi2ir.generators.StatementGenerator.visitCallExpression(StatementGenerator.kt:54)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.jetbrains.kotlin.psi2ir.generators.StatementGenerator.visitDotQualifiedExpression(StatementGenerator.kt:427)
	at org.jetbrains.kotlin.psi2ir.generators.StatementGenerator.visitDotQualifiedExpression(StatementGenerator.kt:54)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.jetbrains.kotlin.psi2ir.generators.StatementGenerator.generateStatement(StatementGenerator.kt:70)
	at org.jetbrains.kotlin.psi2ir.generators.StatementGenerator.generateExpression(StatementGenerator.kt:83)
	at org.jetbrains.kotlin.psi2ir.generators.BodyGenerator.generateExpressionBody(BodyGenerator.kt:93)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateDelegatedImplementationMembers(ClassGenerator.kt:220)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateMembersDeclaredInSupertypeList(ClassGenerator.kt:192)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass(ClassGenerator.kt:99)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass$default(ClassGenerator.kt:63)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassOrObjectDeclaration(DeclarationGenerator.kt:108)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:53)
	... 47 more
```

Generated code causing that:

```java
// Automatically generated file. DO NOT MODIFY
@file:Suppress(
  "DEPRECATION",
  "OPT_IN_USAGE",
  "OPT_IN_USAGE_ERROR",
)

package pl.jsyty.architecturetemplate

import com.deliveryhero.whetstone.SingleIn
import com.deliveryhero.whetstone.app.ApplicationComponent
import com.deliveryhero.whetstone.app.ApplicationScope
import com.squareup.anvil.annotations.MergeComponent
import dagger.Component
import javax.inject.Singleton
import kotlin.Suppress

@MergeComponent(ApplicationScope::class)
@SingleIn(ApplicationScope::class)
@Singleton
public interface GeneratedApplicationComponent : ApplicationComponent {
  @Component.Factory
  public interface Factory : ApplicationComponent.Factory

  public companion object Default : Factory by DaggerGeneratedApplicationComponent.factory()
}
```

Offending line is: `public companion object Default : Factory by DaggerGeneratedApplicationComponent.factory()`, specially the last `factory()` call.

Repro is here: https://github.com/jakoss/AndroidArchitectureTemplate/pull/85

**Comment by msfjarvis** [comment]
FWIW Whetstone itself does not use Kotlin 1.8.20 at the moment, but even after [upgrading the project to 1.8.20](https://github.com/msfjarvis/whetstone/pull/17/files) the [error persists](https://github.com/msfjarvis/whetstone/actions/runs/4706215287/jobs/8347295577?pr=17). I came across [KT-44843](https://youtrack.jetbrains.com/issue/KT-44843) which matches the bug we're running into but it was fixed in Kotlin 1.6 and shouldn't be happening anymore.

**Comment by msfjarvis** [comment]
Looks like this was [fixed](https://youtrack.jetbrains.com/issue/KT-58027) in Kotlin 1.8.21

**Comment by JoelWilcox** [comment]
@jakoss do you still see this issue with Kotlin 1.8.21? Technically the current Anvil release only supports 1.8.20, but worth a shot to verify the behavior now.

**Comment by jakoss** [comment]
@JoelWilcox I was waiting for ksp to catch up since i cannot build the project without that. I think it should be ready real soon

**Comment by jakoss** [comment]
@JoelWilcox Failing on another part, i think it's a whetstone failure at this point but i'm not sure. 

```
> Task :app:kaptDebugKotlin
/home/runner/work/AndroidArchitectureTemplate/AndroidArchitectureTemplate/app/build/tmp/kapt3/stubs/debug/pl/jsyty/architecturetemplate/GeneratedApplicationComponent.java:23: error: @BindsInstance parameters may only be used in abstract methods
        android.app.Application application) {
                                ^

> Task :app:kaptDebugKotlin FAILED
```

Full log: https://github.com/jakoss/AndroidArchitectureTemplate/actions/runs/4828945270/jobs/8603392203?pr=95

**Comment by msfjarvis** [comment]
At some point this used to be a [JavaPoet bug](https://github.com/google/dagger/issues/1715), is it possible KotlinPoet is exhibiting the same behaviour?

**Comment by JoelWilcox** [comment]
Hard to tell where the error is coming from at the moment, I'm not personally familiar with Whetstone. If you're able to share a sample project with the issue that only uses Anvil that would be helpful in narrowing it down. Although I understand if that's not feasible in this case.

You could also try the latest Anvil snapshot (2.4.6-SNAPSHOT) to see if that makes any difference, as it targets Kotlin 1.8.21 and the latest KotlinPoet version 1.13.0 (looks like there are already some new bug fix release I need to bump to :)).

One other thing to note is it looks like Whetstone is currently still targeting Kotlin 1.8.10 and Anvil 2.4.4 so there might be conflicts happening there since it's a bit behind if you're upgrading to Anvil 2.4.5.

**Comment by msfjarvis** [comment]
FWIW upgrading to Kotlin 1.8.21 and Anvil 2.4.6 solves this specific problem so this can be closed on Anvil's end.

The problem that Whetstone is running into after the upgrade is coming specifically from [this line](https://github.com/msfjarvis/whetstone/blob/8e9ee397ce858ec8ae6137bbb5d2fd68b4064d4c/whetstone/src/main/java/com/deliveryhero/whetstone/app/ApplicationComponent.kt#L25), where the `android.app.Application` parameter has a `@BindsInstance` annotation, I assume to substitute in the actual Application class at runtime. This is fine, but the generated Java code preserves the annotation in the implementation of this class which is now invalid since the annotation is only allowed on abstract methods.

```
> Task :sample:kaptReleaseKotlin FAILED
/home/msfjarvis/git-repos/whetstone/sample/build/tmp/kapt3/stubs/release/com/deliveryhero/whetstone/sample/GeneratedApplicationComponent.java:29: error: @Component.Factory method has parameters for modules or components that aren't required: [org.jetbrains.annotations.NotNull android.app.Application application]
    public static abstract interface Factory extends com.deliveryhero.whetstone.app.ApplicationComponent.Factory {
                           ^
```

**Comment by JoelWilcox** [comment]
Thanks for testing it out and confirming @msfjarvis. Going to close this but feel free to re-open if additional details come up indicating that there's an issue on the Anvil side.
