### ISSUE TITLE
Nested module compiler error

### ISSUE THREAD

**Issue by Dkhusainov** [square/anvil#85]
```
@Singleton
@MergeComponent(Singleton::class, modules = [MyComponent.Module::class])
interface MyComponent {
  
  @dagger.Module
  abstract class Module
}
```
produces:
```
Caused by: java.lang.IllegalStateException: Recursive call in a lazy value under LockBasedStorageManager@3f27bee2 (TopDownAnalyzer for JVM)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyAnnotationDescriptor.getAllValueArguments(LazyAnnotations.kt)
        at com.squareup.anvil.compiler.UtilsKt.getAnnotationValue(Utils.kt:123)
        at com.squareup.anvil.compiler.UtilsKt.scope(Utils.kt:126)
        at com.squareup.anvil.compiler.InterfaceMerger.addSyntheticSupertypes(InterfaceMerger.kt:36)

```

**Comment by vRallev** [comment]
Unfortunately, there is no workaround. This happens when resolving the super classes for `MyComponet`. The plugin resolves the annotation, because it has to know about the scope and which super types it needs to add. While resolving the annotation is resolves `MyComponent.Module`. Since this is an inner class and `MyComponent` hasn't been resolved yet, it tries to resolve it again. This recursion goes on and on and on. 

I have a test for a similar case: https://github.com/square/anvil/blob/main/compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt#L403-L426

I'll add another one for this explicit case.
