### ISSUE TITLE
K2: hints aren't discoverable in K2 IR

### ISSUE THREAD

**Issue by ZacSweers** [square/anvil#914]
Example trace:

```
> Task :apps:app-startup-di:compileInternalDebugKotlin
e: java.lang.IllegalStateException: Module Module <-apps-app-startup-di> doesn't contain package anvil.hint.subcomponent
        at org.jetbrains.kotlin.fir.descriptors.FirModuleDescriptor.getPackage(FirModuleDescriptor.kt:55)
        at com.squareup.anvil.compiler.codegen.reference.RealAnvilModuleDescriptor.getPackage(RealAnvilModuleDescriptor.kt)
        at com.squareup.anvil.compiler.ClassScanner.findContributedClasses(ClassScanner.kt:37)
        at com.squareup.anvil.compiler.ClassScannerIrKt.findContributedClasses(ClassScannerIr.kt:23)
        at com.squareup.anvil.compiler.ModuleMergerIr.findContributedSubcomponentModules(ModuleMergerIr.kt:386)
```

**Comment by ZacSweers** [comment]
Found the issue, should be simple to work around 👍. Will put up a PR
